logging:
  level: INFO
  path: ./outputs/logs

paths:
## INPUTS  
  finetune_model: ./outputs/finetuning

## OUTPUTS
  calibrated_predictions: ./outputs/calibrated_predictions # Save encoded data to this folder


    

 
