logging:
  level: INFO
  path: ./outputs/logs

paths:
## INPUTS  
  finetune_model: ./outputs/generated/finetune

## OUTPUTS
  calibrated_predictions: ./outputs/generated/calibrated_predictions # Save encoded data to this folder