logging:
  level: INFO
  path: ./outputs/logs

paths:
## INPUTS  
  finetune_model: ./outputs/causal/finetuning_exposure

## OUTPUTS
  encoded_data: ./outputs/causal/encoding # Save encoded data to this folder

loader:
  batch_size: 256
  num_workers: 1
  pin_memory: true
    

 
