logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  ## INPUTS
  calibrated_predictions: ./outputs/causal/finetune/models/simulated/calibrated/
  counterfactual_outcomes: ./outputs/causal/simulated_outcomes # optional

  ## OUTPUTS
  estimate: ./outputs/causal/estimate/simulated

estimator:
  methods: ["IPW", "TMLE"]
  effect_type: "ATE"
  n_bootstrap: 30
  common_support_threshold: 0.001
