logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  data: ./example_data/synthea_meds_causal
  features: ./outputs/causal/data/features

  outcomes: ./outputs/causal/finetune/outcomes

outcomes:
  EXPOSURE:
    type: [code]
    match: [["EXPOSURE"]]
    match_how: exact
    case_sensitive: true

  OUTCOME:
    type: [code]
    match: [["OUTCOME"]]
    match_how: exact
    case_sensitive: false

  OUTCOME_2:
    type: [code]
    match: [["OUTCOME_2"]]
    match_how: exact
    case_sensitive: false

  OUTCOME_3:
    type: [code]
    match: [["OUTCOME_3"]]
    match_how: exact
    case_sensitive: false

  OUTCOME_empty:
    type: [code]
    match: [["000000000"]]
    match_how: exact
    case_sensitive: false

  TEST_EXCLUSION:
    type: [code]
    match: [["D/73438004"]]
    match_how: exact
    case_sensitive: true
    exclusion:
      events:
        type: [code]
        match: [["D/72892002"]]
        match_how: exact
      window_hours_min: -10
      window_hours_max: 10
  TEST_COMBINATION:
    combinations:
      primary:
        type: [code]
        match: [["D/73438004"]]
        match_how: exact
      secondary:
        type: [code]
        match: [["D/72892002"]]
        match_how: exact
      window_hours_min: -10
      window_hours_max: 10
      timestamp_source: primary
