logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  data: ./example_data/synthea_meds_causal
  features: ./outputs/causal/data/features

  outcomes: ./outputs/causal/finetune/outcomes

outcomes:
  EXPOSURE:
    type: [code]
    match: [["EXPOSURE"]]
    match_how: exact
    case_sensitive: true

  OUTCOME:
    type: [code]
    match: [["OUTCOME"]]
    match_how: exact
    case_sensitive: false

  OUTCOME_2:
    type: [code]
    match: [["OUTCOME_2"]]
    match_how: exact
    case_sensitive: false

  OUTCOME_3:
    type: [code]
    match: [["OUTCOME_3"]]
    match_how: exact
    case_sensitive: false
