logging:
  level: INFO
  path: ./outputs/logs

paths:
  data: ./example_data/example_MEDS_data_causal
  outcomes: ./outputs/causal/outcomes
  features: ./outputs/causal/features/

outcomes:
  EXPOSURE: 
    type: [code]
    match: [['EXPOSURE']]
    match_how: contains
    case_sensitive: true
  OUTCOME:
    type: [code]
    match: [['OUTCOME']]
    match_how: startswith
    case_sensitive: false
    
