logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  data: ./example_data/MEDS_correlated_causal
  features: ./outputs/causal/data/features

  outcomes: ./outputs/causal/finetune/outcomes

outcomes:
  EXPOSURE:
    type: [code]
    match: [["EXPOSURE"]]
    match_how: contains
    case_sensitive: true
  OUTCOME:
    type: [code]
    match: [["OUTCOME"]]
    match_how: startswith
    case_sensitive: false
