logging:
  level: INFO
  path: ./outputs/logs

paths:
  data: ./example_data/example_MEDS_data_w_labs
  outcomes: ./outputs/causal/outcomes
  features: ./outputs/features/

outcomes:
  EXPOSURE: 
    type: [code]
    match: [['M37']]
    match_how: contains
    case_sensitive: true
  OUTCOME:
    type: [code]
    match: [['D54']]
    match_how: startswith
    case_sensitive: false
    
