logging:
  level: INFO
  path: ./outputs/logs

paths:
  ### Inputs
  patients_info: ./example_data/example_data_w_labs/patients_info.csv
  initial_pids: ./outputs/tokenized/pids_finetune.pt # Initial patients to select from [list of pids] (optional)
  outcome: ./outputs/causal/outcomes/EXPOSURE.csv # Outcome
  
  ### Outputs
  cohort: ./outputs/causal/exposure_cohort # Data directory

selection:
  exclude_prior_outcomes: false # Exclude patients who had the outcome before index date
  exposed_only: false # Exclude patients who are not exposed
  age:
    min_years: 0 # Minimum age to include (inclusive)
    max_years: 120 # Maximum age to include (inclusive)

index_date: # if not provided we can use exposures to get the index dates
  mode: relative # absolute or relative (to exposure)
  relative: # takes first exposure as index date
    n_hours_from_exposure: 0 # negative means before exposure, 0 by default

cv_folds: 5 # can be set to 1 if only a simple train/val split is needed
test_split: 0 # can be set to 1 for test set creation only
