logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  # input dir
  data: ./example_data/synthea_meds_causal
  splits: ["tuning"]
  # output dir
  outcomes: ./outputs/causal/finetune/simulated_outcomes
seed: 42

exposure:
  code: "EXPOSURE"
  run_in_days: 9000 # when do we start drawing probabilities from the exposure
  p_base: 0.3 # Base 30% chance of exposure over the patient's timeline
  trigger_codes: [D/25675004, D/431855005, D/80583007, D/105531004, D/65363002]
  # Even stronger effects for higher AUROC
  trigger_weights: [2, 2, 2, 2, 2] # [1.5, 2.0, -1.5, 1.0, 0.5] # logits

outcomes:
  OUTCOME:
    code: "OUTCOME"
    run_in_days: 30 # after exposure/non-exposure
    p_base: 0.1
    trigger_codes: [
        D/25675004, # confounder
        D/431855005, # confounder
        D/80583007, # confounder
        D/125605004, # prognostic
        D/384709000, # prognostic
      ]
    # Confounders have a different effect on the outcome than on the exposure.
    trigger_weights: [2.0, 1.0, -1.0, 0.5, 1.5] # logits
    # STRONG positive effect from exposure.
    exposure_effect: 2 # logits

  OUTCOME_2:
    code: "OUTCOME_2"
    run_in_days: 30 # after exposure/non-exposure
    p_base: 0.08
    trigger_codes: [
        D/431855005, # confounder
        D/80583007, # confounder
        D/105531004, # confounder
        D/65363002, # prognostic
        D/384709000, # prognostic
      ]
    trigger_weights: [0.5, 1, -1, 0.5, 1.5] # logits
    # WEAKER positive effect from exposure.
    exposure_effect: 1 # logits

  OUTCOME_3:
    code: "OUTCOME_3"
    run_in_days: 30 # after exposure/non-exposure
    p_base: 0.12
    trigger_codes: [
        D/80583007, # confounder
        D/105531004, # confounder
        D/65363002, # confounder
        D/384709000, # prognostic
      ]
    trigger_weights: [2.0, 1.0, -1.0, 1.5] # logits
    # ZERO direct causal effect from exposure.
    exposure_effect: 0
