logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  # input dir
  data: ./example_data/synthea_meds_causal
  splits: ["tuning"]
  # output dir
  outcomes: ./outputs/causal/simulated_outcomes
seed: 42

simulation_model:
  linear:
    mean: 0
    scale: 0.5
  interaction:
    mean: 0
    scale: 0.5
  linear_subset_size: 20_000
  interaction_subset_size: 1000

exposure:
  p_base: 0.3 # Base 15% chance of exposure over the patient's timeline

outcomes:
  OUTCOME:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.1
    exposure_effect: 3 # logits

  OUTCOME_2:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.1
    # WEAKER positive effect from exposure.
    exposure_effect: 2 # logits

  OUTCOME_3:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.1
    # ZERO direct causal effect from exposure.
    exposure_effect: 1

  OUTCOME_4:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.1
    # ZERO direct causal effect from exposure.
    exposure_effect: 0
# unobserved_confounder:
#   p_occurrence: 0.1
#   exposure_effect: 0.01
#   outcome_effects:
#     OUTCOME_4: 0.1
