logging:
  level: INFO
  path: ./outputs/logs

paths:
## INPUTS  
  encoded_data: ./outputs/causal/encoding
  calibrated_predictions: ./outputs/causal/calibrated_predictions

## OUTPUTS
  simulated_outcome: ./outputs/causal/simulated_outcome_enc_strong

simulation:
  exposure_coef: 1 # exposure coefficient
  enc_coef: .01 # treatment patient embeddings coefficient
  intercept: -1 # intercept
  enc_sparsity: 0.7 # proportion of treatment patient embeddings that will have non-zero coefficients
  enc_scale: 0.01 # scale of the normal distribution for treatment patient embeddings coefficients
 
