logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  # input dir
  data: ./example_data/synthea_meds_causal
  splits: ["tuning"]
  # output dir
  outcomes: ./outputs/causal/simulated_outcomes
seed: 42

trigger_codes:
  [D/312608009, D/431856006, D/55822004, D/267020005, D/157141000119108]

simulation_model: # use laplace distribution
  linear:
    mean: 0
    scale: 0.5
  interaction:
    mean: 0
    scale: 0.5

exposure:
  p_base: 0.15 # Base 15% chance of exposure over the patient's timeline

outcomes:
  OUTCOME:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.1
    exposure_effect: 2 # logits

  OUTCOME_2:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.08
    # WEAKER positive effect from exposure.
    exposure_effect: 1 # logits

  OUTCOME_3:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.12
    # ZERO direct causal effect from exposure.
    exposure_effect: 0
  OUTCOME_4:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.12
    # ZERO direct causal effect from exposure.
    exposure_effect: 0

unobserved_confounder:
  p_occurrence: 0.2
  exposure_effect: 0.3
  outcome_effects:
    OUTCOME_4: 0.3
