logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  # input dir
  data: ./example_data/synthea_meds_causal
  splits: ["tuning"]
  # output dir
  outcomes: ./outputs/causal/simulated_outcomes
seed: 42

exposure:
  p_base: 0.3 # Base 30% chance of exposure over the patient's timeline
  trigger_codes:
    [D/312608009, D/431856006, D/55822004, D/267020005, D/157141000119108]
  # Even stronger effects for higher AUROC
  trigger_weights: [2, 2, 2, 2, 2] # [1.5, 2.0, -1.5, 1.0, 0.5] # logits

outcomes:
  OUTCOME:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.1
    trigger_codes: [
        D/312608009, # confounder
        D/431856006, # confounder
        D/55822004, # confounder
        D/713458007, # prognostic
        D/44465007, # prognostic
      ]
    # Confounders have a different effect on the outcome than on the exposure.
    trigger_weights: [2.0, 1.0, -1.0, 0.5, 1.5] # logits
    # STRONG positive effect from exposure.
    exposure_effect: 2 # logits

  OUTCOME_2:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.08
    trigger_codes: [
        D/431856006, # confounder
        D/55822004, # confounder
        D/267020005, # confounder
        D/433144002, # prognostic
        D/224295006, # prognostic
      ]
    trigger_weights: [0.5, 1, -1, 0.5, 1.5] # logits
    # WEAKER positive effect from exposure.
    exposure_effect: 1 # logits

  OUTCOME_3:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.12
    trigger_codes: [
        D/55822004, # confounder
        D/267020005, # confounder
        D/157141000119108, # confounder
        D/840544004, # prognostic
      ]
    trigger_weights: [2.0, 1.0, -1.0, 1.5] # logits
    # ZERO direct causal effect from exposure.
    exposure_effect: 0
