logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  # input dir
  data: ./example_data/synthea_meds_causal
  splits: ["tuning"]
  # output dir
  outcomes: ./outputs/causal/simulated_outcomes

seed: 42
debug: true

include_code_prefixes: ["D/"]

simulation_model:
  time_decay_halflife_days: 9000
  linear:
    mean: 0
    scale: 0.9
    max_weight: 2.0
    sparsity_factor: 0
  interaction:
    mean: 0
    scale: 0.9
    max_weight: 2.0
    sparsity_factor: 0.6

exposure:
  p_base: 0.3 # Base 15% chance of exposure over the patient's timeline
  age_effect: 0.005 # logit increase per year of age

outcomes:
  OUTCOME:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.1
    exposure_effect: 3 # logits
    age_effect: -0.005

  OUTCOME_2:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.1
    # WEAKER positive effect from exposure.
    exposure_effect: 2 # logits

  OUTCOME_3:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.1
    # ZERO direct causal effect from exposure.
    exposure_effect: 1

  OUTCOME_4:
    run_in_days: 1 # after exposure/non-exposure
    p_base: 0.1
    # ZERO direct causal effect from exposure.
    exposure_effect: 0
# unobserved_confounder:
#   p_occurrence: 0.1
#   exposure_effect: 0.01
#   outcome_effects:
#     OUTCOME_4: 0.1
