delays:
  days: 14 # we match diagnoses and register diagnoses up to index_date + delay_days/ assume it is not caused by the trial drug
  code_groups:
    - "D/" # diagnoses
    - "RD/" # register diagnoses

min_age: 50 # minimum age for inclusion  

inclusion_criteria:
  strict:
    - type2_diabetes
    - glycemic_control
    # at max two unique anti-diabetic drugs should be present. Think about how to do this best.
  minimum_one:
    - myocardial_infarction
    - stroke
    - transient_ischemic_attack
    - arterial_revascularization
    - chronic_renal_impairment
    
exclusion_criteria:
  - type1_diabetes
  - glp1_receptor_agonist
  - dpp4_inhibitor
  - acute_decompensation_of_glycemic_control
  - cancer
  - end_stage_liver_disease
  - insulin
  - pregnancy_and_birth

# we always check for both normal and register medication/diagnoses as well as for all procedures P, RPO, RPS
criteria_definitions:
  # Inclusion Criteria (At least one of the following should be true)
  type2_diabetes:
    use_patterns:
      - metformin
      - dpp4_inhibitors
      - sglt2_inhibitors
      - sulphonylureas
      - thiazolidinediones
    codes:
      - ^(?:D|RD)/C11.*

  myocardial_infarction:
    codes:
      - ^(?:D|RD)/I2[1-3].*  # starts with D/I21, D/I22, D/I23

  stroke:
    codes:
      - ^(?:D|RD)/I6[3-6].*  # starts with D/I63, D/I64, D/I65, D/I66
      - ^(?:D|RD)/H341.*     # starts with D/H341

  transient_ischemic_attack:
    codes:
      - ^(?:D|RD)/G45.*      # starts with D/G45

  arterial_revascularization:
    codes:
      - ^(?:P|RPO|RPS)/KFNG.*
      - ^(?:P|RPO|RPS)/KFNF.*

  chronic_renal_impairment:
    codes:
      - ^L/.*egfr.*1[.,]73.*
    threshold: 60
    operator: "<="
      
  # Glycemic Control
  glycemic_control:
    codes:
      - ^L/.*hba1c.*
    threshold: 7.0
    operator: ">="


  #########################################################################
  # Exclusion Criteria (Remove if at least one of the following is true)
  type1_diabetes:
    codes:
      - ^D/C10.*

  glp1_receptor_agonist:
    codes:
      - ^(?:M|RM)/A10BJ02.*  # Liraglutide
      - ^(?:M|RM)/A10BJ05.*  # Dulaglutid
      - ^(?:M|RM)/A10BJ06.*  # Semaglutide
      - ^(?:M|RM)/A10AE56.*  # Insulin/Liraglutid combination
    time_window_days: 90

  dpp4_inhibitor:
    use_patterns:
      - dpp4_inhibitors
    time_window_days: 30

  insulin: 
    codes:
      - ^(?:M|RM)/A10A.*
    time_window_days: 90

  acute_decompensation_of_glycemic_control:
    codes: 
      - ^(?:D|RD)/E111.* # ketoacidosis
      - ^(?:D|RD)/E121.* # hyperosmolar hyperglycemic state
      - ^(?:D|RD)/E131.* # diabetic coma
      - ^(?:D|RD)/E141.* # diabetic ketoacidosis
    time_window_days: 90
  chronic_pancreatitis:
    codes:
      - ^(?:D|RD)/K861.*
    time_window_days: 730 # 2 years

  idiopathic_acute_pancreatitis:
    codes:
      - ^(?:D|RD)/K850.*
    time_window_days: 730 # 2 years

  acute_coronary_or_cv_event:
    codes:
      - ^(?:D|RD)/I2[1-2].*
      - ^(?:D|RD)/I24.*
      - ^(?:D|RD)/I6[3-6].*
    time_window_days: 90

  chronic_hemodialysis: # includes peritoneal dialysis
    codes:
      - ^(?:D|RD)/N185.*

  end_stage_liver_disease:
    codes:
      - ^(?:D|RD)/K72.* # this will have more potentially, e.g. + bilirubin, albumin, etc. # need to handle this in a smart way
      # it will be a combination of acute/chronic liver disease + one of the other criteria
    
  solid_organ_transplant:
    codes:
      - ^(?:D|RD)/Z94.*

  cancer:
    codes: # DC00-DC99 (except C4491/2)
      - ^(?:D|RD)/C[0-9][0-9].*
    exclude_codes:
      - ^(?:D|RD)/C449.*
    time_window_days: 1826 # 5 years

  multiple_endocrine_neoplasia:
    codes:
      - ^(?:D|RD)/E312.* # ?
    time_window_days: 1826 # 5 years

  medullary_thyroid_carcinoma:
    codes:
      - ^(?:D|RD)/D093.*
    time_window_days: 1826 # 5 years

  calcitonin_elevated:
    codes:
      - ^L/CALCITONIN.*
    time_window_days: 1826 # 5 years

  pregnancy_and_birth:
    codes:
      - ^(?:D|RD)/O[0-9][0-9].*

# Define reusable code patterns
code_patterns:
  metformin:
    codes:
      - ^(?:M|RM)/A10BA.*
      - ^(?:M|RM)/A10BD0[1-3].*
      - ^(?:M|RM)/A10BD05.*

  dpp4_inhibitors:
    codes:
      - ^(?:M|RM)/A10BH.*
      - ^(?:M|RM)/A10BD0[7-9].*
      - ^(?:M|RM)/A10BD1[0-3].*

  sglt2_inhibitors:
    codes:
      - ^(?:M|RM)/A10BK.*
      - ^(?:M|RM)/A10BD1[5-6].*

  sulphonylureas:
    codes:
      - ^(?:M|RM)/A10BB.*
      - ^(?:M|RM)/A10BC.*

  thiazolidinediones:
    codes:
      - ^(?:M|RM)/A10BG.*

# Use the same patterns for unique code limits
unique_code_limits:
  anti_diabetic_drugs:
    max_count: 2
    use_patterns:
      - metformin
      - sulphonylureas
      - sglt2_inhibitors
      - thiazolidinediones



  








