# provide expressions for inclusion and exclusion
inclusion: type2_diabetes & adult
exclusion: type1_diabetes

criteria_definitions:
  adult:
    min_age: 18

  type2_diabetes:
    codes:
    - ^(?:D|RD)/DC11.*
    - ^(?:M|RM)/A10B.*

  type1_diabetes:
    codes:
    - ^(?:D|RD|RPO)/DE10.*
