# provide expressions for inclusion and exclusion
inclusion: "min_age_50 & diabetes_treatment"
exclusion: type1_diabetes

criteria_definitions:
  # Define all the criteria that will be needed. You can easily create composite criteria using expressions.
  min_age_50:
    # would be the age at index_date
    min_age: 50

  diabetes_treatment:
    codes:
    - ^(?:M|RM)/A10.*

  type1_diabetes:
    codes:
    - ^(?:D|RD|RPO)/DE10.*

delays:
  days: 14 # we match diagnoses and register diagnoses up to index_date + delay_days/ assume it is not caused by the trial drug
  code_groups:
  - "D/" # diagnoses
  - "RD/" # register diagnoses
