logging:
  level: INFO
  path: ./outputs/logs

paths:
  ### Inputs
  cohort: ./outputs/causal/finetune/cohorts/full # Data directory
  meds: ./example_data/MEDS_correlated_causal
  splits: [tuning]
  criteria_definitions_config: ./corebehrt/configs/causal/helper/criteria_definitions.yaml
  ### Outputs
  criteria: ./outputs/causal/finetune/criteria_for_stats # Data directory
