logging:
  level: INFO
  path: ./outputs/logs

paths:
  ### Inputs
  criteria: ./outputs/causal/finetune/criteria_for_stats # should contain criteria.csv

  #### Optional
  cohort: ./outputs/causal/finetune/cohorts/full # should contain pids.pt
  ps_calibrated_predictions: ./outputs/causal/finetune/models/simple/calibrated/predictions_exposure # should contain predictions_and_targets_calibrated.csv
  outcome_model: ./outputs/causal/finetune/models/simple/calibrated/predictions_outcome/OUTCOME # should contain predictions_and_targets_calibrated.csv ! needs to be updated to use ft_exp

  ### Outputs
  stats: ./outputs/causal/finetune/stats

# optional
weights: ATE # chose from ATE, ATT, ATC or null
common_support_threshold: 0.001 # only used if weights is not null
plot_ps: true
