logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  ## INPUTS
  calibrated_predictions: ./outputs/causal/finetune/models/exp_y/calibrated/
  # counterfactual_outcomes: ./outputs/causal/counterfactual_outcomes # optional

  ## OUTPUTS
  estimate: ./outputs/causal/estimate/simple

estimator:
  methods: ["IPW", "AIPW", "TMLE"]
  effect_type: "ATE"
  n_bootstrap: 30
  common_support_threshold: 0.001
