exposure:
  code: EXPOSURE
  compliance_interval_days: 90
  min_compliance_days: 365
  p_base: 0.15
  run_in_days: 365
  trigger_codes:
  - D/25675004
  - D/431855005
  - D/80583007
  - D/105531004
  - D/65363002
  trigger_weights:
  - 1.5
  - 2.0
  - -1.5
  - 1.0
  - 0.5
outcomes:
  outcome_1:
    code: OUTCOME
    exposure_effect: 2
    p_base: 0.1
    run_in_days: 30
    trigger_codes:
    - D/25675004
    - D/431855005
    - D/80583007
    - D/125605004
    - D/384709000
    trigger_weights:
    - 2.0
    - 1.0
    - -1.0
    - 0.5
    - 1.5
  outcome_2:
    code: OUTCOME_2
    exposure_effect: 1
    p_base: 0.08
    run_in_days: 30
    trigger_codes:
    - D/431855005
    - D/80583007
    - D/105531004
    - D/65363002
    - D/384709000
    trigger_weights:
    - 0.5
    - 1
    - -1
    - 0.5
    - 1.5
  outcome_3:
    code: OUTCOME_3
    exposure_effect: 0
    p_base: 0.12
    run_in_days: 30
    trigger_codes:
    - D/80583007
    - D/105531004
    - D/65363002
    - D/65363002
    - D/384709000
    trigger_weights:
    - 2.0
    - 1.0
    - -1.0
    - 0.5
    - 1.5
paths:
  source_dir: ./example_data/synthea_meds
  splits:
  - train
  - tuning
  - held_out
  write_dir: ./example_data/synthea_meds_causal
