# provide expressions for inclusion and exclusion
inclusion: min_age_0 | criteria_1 # use |, &, ~, and, or, ~ together with criteria names separated by space to create arbitrary inclusion criteria
exclusion: min_age_99

criteria_definitions:
  # Define all the criteria that will be needed. You can easily create composite criteria using expressions.
  min_age_0:
    # would be the age at index_date
    min_age: 0

  min_age_99:
    min_age: 99

  criteria_1:
    codes:
      # Diagnosis codes
      - ^D/431855005.*
    start_days: -1
    end_days: 10_000
