# provide expressions for inclusion and exclusion
inclusion: min_age_5 | criteria_1 # use |, &, ~, and, or, ~ together with criteria names separated by space to create arbitrary inclusion criteria
exclusion: min_age_80

criteria_definitions:
  # Define all the criteria that will be needed. You can easily create composite criteria using expressions.
  min_age_5:
    # would be the age at index_date
    min_age: 5

  min_age_80:
    min_age: 85

  criteria_1:
    codes:
      # Diagnosis codes
      - ^DE11.*
    start_days: -100
    end_days: 100
