# provide expressions for inclusion and exclusion
inclusion: min_age_10 | criteria_1 # use |, &, ~, and, or, ~ together with criteria names separated by space to create arbitrary inclusion criteria
exclusion: max_age_90

criteria_definitions:
  # Define all the criteria that will be needed. You can easily create composite criteria using expressions.
  min_age_10:
    # would be the age at index_date
    min_age: 10

  max_age_90:
    max_age: 90

  criteria_1:
    codes:
      # Diagnosis codes
      - ^D84.*
    exclude_codes:
      - ^D84.1.*
    start_days: -1
    end_days: 1
