logging:
  level: INFO
  path: ./outputs/logs

paths:
## INPUTS
  data: ./example_data/example_MEDS_data_w_labs
      
## OUTPUTS
  counts: ./outputs/counts # Save counts to this folder
  
splits: [train, tuning]