logging:
  level: INFO
  path: ./outputs/logs

paths:
## INPUTS
  code_counts: ./outputs/counts # Folder containing the code counts
      
## OUTPUTS
  mapping: ./outputs/mapping # Save mapping to this folder

file: code_counts.json # File containing the code counts (optional, default is code_counts.json)

threshold: 90
hierarchical_pattern: ^(?:M|D|P) # codes starting with M, D, P 
separator: "/"
