logging:
  level: INFO
  path: ./outputs/logs

outcomes:
  EXPOSURE:
    type: [ code ]
    match: [ [ 'EXPOSURE' ] ]
    match_how: contains
    case_sensitive: true
  OUTCOME:
    type: [ code ]
    match: [ [ 'OUTCOME' ] ]
    match_how: startswith
    case_sensitive: false
