# provide expressions for inclusion and exclusion
inclusion: min_age_50 & criteria_1 | ~ criteria_2 # use |, &, ~, and, or, ~ together with criteria names separated by space to create arbitrary inclusion criteria
exclusion: max_age_60 & criteria_3 & criteria_4

criteria_definitions:
  # Define all the criteria that will be needed. You can easily create composite criteria using expressions.
  min_age_50:
    # would be the age at index_date
    min_age: 50

  max_age_60:
    max_age: 60

  criteria_1:
    codes:
      # Diagnosis codes
      - ^D/25675004.*
    start_days: -365
    end_days: 0
  criteria_2:
    codes:
      - ^D/431855005.*

  count_criteria_1:
    unique_criteria_list:
      - criteria_1
      - criteria_2
    min_count: 1

  criteria_3:
    expression: criteria_1 | criteria_2

  criteria_4:
    expression: ~ criteria_3

  criteria_5:
    expression: criteria_1
