logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  ## INPUTS
  features: ./outputs/causal/features
  tokenized: ./outputs/causal/tokenized
  cohort: ./outputs/causal/exposure_cohort # path to cohort directory

  exposures: ./outputs/causal/outcomes
  exposure: EXPOSURE.csv

  outcomes: ./outputs/causal/outcomes
  outcome: OUTCOME.csv

  ## OUTPUTS
  prepared_data: ./outputs/causal/finetuning/prepared_data # Save model/outputs to this folder
  #runs: ./outputs/pretraining # Use for generating a new model folder

data:
  truncation_len: 32
  min_len: 2 # 0 by default

exposure:
  # we will convert outcomes to binary based on whether at least one outcome is in the follow up window
  n_hours_censoring: -10 # censor time after index date (negative means before)
  n_hours_start_follow_up: -1 # start follow up (considering outcomes) time after index date (negative means before)
  n_hours_end_follow_up: null # end follow up (considering outcomes) time after index date (negative means before)

outcome:
  n_hours_start_follow_up: 100 # start follow up (considering outcomes) time after index date (negative means before)
  n_hours_end_follow_up: null # end follow up (considering outcomes) time after index date (negative means before)
