logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  ## INPUTS
  finetune_model: ./outputs/causal/finetune/models/simple

  ## OUTPUTS
  calibrated_predictions: ./outputs/causal/finetune/models/simple/calibrated

plotting:
  plot_all_outcomes: True
  # num_outcomes_to_plot: 5
