logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  ## INPUTS
  finetune_model: ./outputs/causal/finetune/models/simulated

  ## OUTPUTS
  calibrated_predictions: ./outputs/causal/finetune/models/simulated/calibrated
