logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  ## INPUTS
  pretrain_model: ./outputs/causal/pretrain/model
  prepared_data: ./outputs/causal/finetune/processed_data/exposure

  ## OUTPUTS
  model: ./outputs/causal/finetune/models/exposure # Save model/outputs to this folder
  #runs: ./outputs/pretraining # Use for generating a new model folder

model:
  cls:
    _target_: ehr2vec.model.heads.ClassifierGRU
    bidirectional: true

trainer_args:
  sampler_function:
    _target_: corebehrt.modules.trainer.utils.Sampling.inverse_sqrt
  batch_size: 256
  val_batch_size: 256
  effective_batch_size: 256
  epochs: 8
  info: true
  gradient_clip:
    clip_value: 1.0
  shuffle: true
  checkpoint_frequency: 1
  early_stopping: 3
  stopping_criterion: roc_auc

optimizer:
  lr: 1e-2
  eps: 1e-6

scheduler:
  _target_: transformers.get_constant_schedule_with_warmup
  num_warmup_epochs: 2

metrics:
  roc_auc:
    _target_: corebehrt.modules.monitoring.metrics.ROC_AUC
  pr_auc:
    _target_: corebehrt.modules.monitoring.metrics.PR_AUC
