logging:
  level: INFO
  path: ./outputs/logs/causal_multitarget

paths:
  data: ./example_data/MEDS_correlated_causal
  features: ./outputs/causal/data/features

  outcomes: ./outputs/causal_multitarget/finetune/outcomes

outcomes:
  E1:
    type: [code]
    match: [["M864"]]
    match_how: contains
    case_sensitive: true
  E2:
    type: [code]
    match: [["M139"]]
    match_how: startswith
    case_sensitive: false
  E3:
    type: [code]
    match: [["M516"]]
    match_how: startswith
    case_sensitive: false
  E4:
    type: [code]
    match: [["M905"]]
    match_how: startswith
    case_sensitive: false
