logging:
  level: INFO
  path: ./outputs/logs/causal

paths:
  data: ./example_data/MEDS_correlated_causal
  tokenized: ./outputs/causal/data/tokenized
  features: ./outputs/causal/data/features
  # optional
  # code_mapping: ./outputs/code_mapping.pt
  # vocabulary: ./outputs/vocabulary # vocab folder

features:
  values:
    value_creator_kwargs:
      num_bins: 10

tokenizer:
  sep_tokens: true
  cls_token: true

excluder:
  min_age: -1
  max_age: 120
