name: 'Test the calibrate step with generated data.'

on:
    workflow_dispatch:
    pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
    tests:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup dependencies.
              run: |
                python -m venv .venv
                source .venv/bin/activate
                pip install -r requirements.txt

            - name: generate_mock_finetune_output
              run: |
                source .venv/bin/activate
                python -m tests.data_generation.generate_finetune_output --output_dir outputs/generated/finetune

            - name: calibrate
              run: |
                source .venv/bin/activate
                python -m corebehrt.main_causal.calibrate --config_path ./corebehrt/configs/causal/calibrate_mock.yaml

            - name: test_calibrate_result
              run: |
                source .venv/bin/activate
                python -m tests.test_main_causal.test_calibrate_result --finetune_dir outputs/generated/finetune --calibrated_dir outputs/generated/calibrated


