name: 'Causal Pipeline Performance 2 Target Test Uncensored'

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # ─── Setup ───────────────────────────────────────────
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clean outputs & create venv
        run: |
          rm -rf ./outputs/causal
          python -m venv .venv
          echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Set Python path
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      # ─── Pipeline & Tests ────────────────────────────────────
      - name: Data prep & pretrain
        shell: bash
        run: |
          set -euo pipefail
          source .github/workflows/pipeline_helpers.sh

          run_step main.create_data prepare_and_pretrain/create_data.yaml
          run_step main.prepare_training_data prepare_and_pretrain/prepare_pretrain.yaml
          run_step main.pretrain prepare_and_pretrain/pretrain.yaml
          run_step main.create_outcomes outcomes.yaml
          run_step main_causal.select_cohort_full select_cohort_full/extract.yaml

      - name: Prepare Finetune Data
        shell: bash
        run: |
          set -euo pipefail
          source .github/workflows/pipeline_helpers.sh
          run_step main_causal.prepare_training_data multitarget/prepare/simple.yaml
          
      - name: Finetune Exposure Uncensored
        shell: bash
        run: |
          set -euo pipefail
          source .github/workflows/pipeline_helpers.sh
          run_step main_causal.finetune_exp_y multitarget/finetune/simple.yaml
          python -m tests.pipeline.test_performance ./outputs/causal_multitarget/finetune/models/simple --min 0.85
          
          
         
          
