name: 'Causal Pipeline test criteria and stats'

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      # ─── Setup ───────────────────────────────────────────
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clean outputs & create venv
        run: |
          rm -rf ./outputs/causal
          python -m venv .venv
          echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: pip install --no-cache-dir -r requirements.txt
      - name: Set Python path
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      # ─── Pipeline & Tests ────────────────────────────────────
      - name: Data prep & pretrain
        shell: bash
        run: |
          set -euo pipefail
          source .github/workflows/pipeline_helpers.sh
          
          run_step main.create_data                         prepare_and_pretrain/create_data.yaml

      - name: Outcomes & cohort selection
        shell: bash
        run: |
          set -euo pipefail
          source .github/workflows/pipeline_helpers.sh
          
          run_step main.create_outcomes                     outcomes.yaml
          run_step main_causal.select_cohort_full           select_cohort_full/extract.yaml

      - name: Prepare Finetune Data
        shell: bash
        run: |
          set -euo pipefail
          source .github/workflows/pipeline_helpers.sh
          run_step main_causal.prepare_ft_exp_y      multitarget/prepare/simple.yaml
        
      - name: Criteria and stats
        shell: bash
        run: |
          set -euo pipefail
          source .github/workflows/pipeline_helpers.sh
          
          run_step main_causal.select_cohort_full                      select_cohort_full/extract.yaml
          run_step main_causal.helper_scripts.extract_criteria helper/extract_criteria.yaml
          run_step main_causal.helper_scripts.get_stats helper/get_stats.yaml
