name: Code counts test

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Generate test fixtures
        run: |
          source .venv/bin/activate
          python tests/data_generation/code_counts_test_setup.py

      - name: Run code counts
        run: |
          source .venv/bin/activate
          python -m corebehrt.main.helper_scripts.get_code_counts --config_path tmp/configs/get_counts.yaml

      - name: Compare code counts output
        run: |
          source .venv/bin/activate
          python tests/helpers/compare_dicts.py --actual tmp/counts/code_counts.json --expected tmp/expected/expected_counts.json

      - name: Run rare-code mapping
        run: |
          source .venv/bin/activate
          python -m corebehrt.main.helper_scripts.map_rare_codes --config_path tmp/configs/map_rare_codes.yaml

      - name: Compare mapping output
        run: |
          source .venv/bin/activate
          python tests/helpers/compare_dicts.py --actual tmp/mapping/rare_code_mapping.pt --expected tmp/expected/expected_mapping.json
