
name: 'Test the estimate step with generated data.'

on:
    workflow_dispatch:
    pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
    tests:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup dependencies.
              run: |
                python -m venv .venv
                source .venv/bin/activate
                pip install -r requirements.txt

            - name: generate_data
              run: |
                source .venv/bin/activate
                python -m tests.data_generation.generate_estimate_data
                
            - name: estimate_with_generated_data
              run: |
                source .venv/bin/activate
                python -m corebehrt.main_causal.estimate --config_path ./corebehrt/configs/causal/estimate/estimate_generated_data.yaml

            - name: test_estimate_result
              run: |
                source .venv/bin/activate
                python -m tests.test_main_causal.test_estimate_result --margin 0.02
