name: 'Pipeline test'

on:
    workflow_dispatch:
    pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
    tests:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup dependencies.
              run: |
                python -m venv .venv
                source .venv/bin/activate
                pip install -r requirements.txt

            - name: main.create_data
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.create_data
            
            - name: main.pretrain
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.pretrain
            
            - name: main.create_outcomes
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.create_outcomes --config_path ./corebehrt/configs/causal/outcomes.yaml

            - name: main.select_cohort_exposure
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.select_cohort --config_path ./corebehrt/configs/causal/select_cohort_exposure.yaml

            - name: main.finetune_exposure
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.finetune_cv --config_path ./corebehrt/configs/causal/finetune_exposure.yaml

            - name: calibrate
              run: |
                source .venv/bin/activate
                python -m corebehrt.main_causal.calibrate 

            - name: encode
              run: |
                source .venv/bin/activate
                python -m corebehrt.main_causal.encode

            - name: train_mlp
              run: |
                source .venv/bin/activate
                python -m corebehrt.main_causal.train_mlp

            - name: estimate
              run: |
                source .venv/bin/activate
                python -m corebehrt.main_causal.estimate

            # With counterfactual outcomes

            - name: simulate
              run: |
                source .venv/bin/activate
                python -m corebehrt.main_causal.simulate

            - name: train_mlp_simulated
              run: |
                source .venv/bin/activate
                python -m corebehrt.main_causal.train_mlp --config_path ./corebehrt/configs/causal/train_mlp_simulated.yaml

            - name: estimate_with_true
              run: |
                source .venv/bin/activate
                python -m corebehrt.main_causal.estimate --config_path ./corebehrt/configs/causal/estimate_with_true.yaml

