name: 'Pipeline test'

on:
    workflow_dispatch:
    pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
    tests:
        runs-on: "ubuntu-latest"
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup dependencies.
              run: |
                python -m venv .venv
                source .venv/bin/activate
                pip install -r requirements.txt

            - name: main.create_data
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.create_data
            
            - name: main.pretrain
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.pretrain
            
            - name: main.create_outcomes
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.create_outcomes
            
            - name: main.select_cohort
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.select_cohort

            - name: main.finetune_cv
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.finetune_cv

            ### Causal ###
            - name: main.create_outcomes
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.create_outcomes --config_path ./corebehrt/configs/causal/outcomes.yaml

            - name: main.select_cohort_exposure
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.select_cohort --config_path ./corebehrt/configs/causal/select_cohort_exposure.yaml

            - name: main.finetune_exposure
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.finetune_cv --config_path ./corebehrt/configs/causal/finetune_exposure.yaml

            - name: main.calibrate
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.main_causal.calibrate 

            - name: main.encode
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.main_causal.encode

            - name: main.simulate
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.main_causal.simulate

            - name: main.finetune_predefined
              run: |
                source .venv/bin/activate
                python -m corebehrt.main.finetune_cv --config_path ./corebehrt/configs/finetune_predefined.yaml
